#!/bin/bash

IIOPATH="/sys/bus/iio/devices"
IIODEVICE=""
for f in `find $IIOPATH/*/* -name "name"`
do 
	if [ `cat $f` == "accel_3d" ]
	then 
		IIODEVICE=`dirname $f`
	fi
done

#echo $IIODEVICE
screenRotationOld="normal"

while true
do
	screenRotation=`inspironReadSensor $IIODEVICE`

	# Only run inspironRotateScreen when the orientation has changed
	if [ "$screenRotation" != "$screenRotationOld" ]
	then
		screenRotationOld=$screenRotation
		inspironRotateScreen "$screenRotation"
	fi

	sleep 5
done
